// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykchfsqgieklkkxdphuq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrY2hmc3FnaWVrbGtreGRwaHVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyMjU3NDQsImV4cCI6MjA1NjgwMTc0NH0.D0Scp80cJVGP63Hnsio00zh1wRDCLeeAiz7O3ILNCgQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);